### ISSUE TITLE
[Ques]仕様を理解してメソッド使えてますか？

### ISSUE THREAD

**Issue by chinen-eita-FTC** [kikuta-reo-FTC/training#15]
https://github.com/kikuta-reo-FTC/training/blob/192f2eeedac12723862a7f070857fa60a6acd6ac/calculate.java#L8-L9

下記の内容が正しい使い方だと思うよ
```
 public static boolean isEvenValue(BigInteger figure){ 
   BigInteger Answer = figure.remainder(second);
```
[remainderメソッドの仕様](https://docs.oracle.com/javase/jp/8/docs/api/java/math/BigInteger.html#remainder-java.math.BigInteger-)

**Comment by kikuta-reo-FTC** [comment]
大変恐縮ですがお手すきの時に、valの意味を教えて頂けると幸いです。

**Comment by chinen-eita-FTC** [comment]
`val` は引数に割り当てている変数名で `value` を省略しただけだよ。

```
public BigInteger remainder(BigInteger val)
値が(this % val)であるBigIntegerを返します。
パラメータ:
val - このBigIntegerを除算する値、および計算された剰余。
戻り値:
this % val
例外:
ArithmeticException - valが0の場合。
```

上記のドキュメントの内容だと、 `BigInteger` クラスの `remainder` メソッドは引数に `BigInteger` 型の値を入力して使ってねてことだよ。

**Comment by chinen-eita-FTC** [comment]
最新のコードに反映されたことを確認したため完了
