### ISSUE TITLE
[Ques] int(プリミティブ)ではなくBigInteger(ラッパークラス)を使用する理由は？

### ISSUE THREAD

**Issue by chinen-eita-FTC** [kikuta-reo-FTC/training#3]
https://github.com/kikuta-reo-FTC/training/blob/192f2eeedac12723862a7f070857fa60a6acd6ac/calculate.java#L5

**Comment by kikuta-reo-FTC** [comment]
intとBigIntegerは比較出来ませんでした。
BigIntegerを採用した理由としましては、数字の桁が10を超えてしまうと
例外処理されてしまうからです。

**Comment by chinen-eita-FTC** [comment]
@kikuta-reo-FTC 
仕様として `10桁以上の整数値` をカバーする必要ある？
例外を吐くから型を変更するのではなく `仕様` があるから型変更することが業務としては正しくないかな？
例外吐くからという理由なら `catch` して `10桁以上の整数値は入力できません` などのメッセージだして回避してもよいかなー

**Comment by kikuta-reo-FTC** [comment]
そうですね。
現在、BIgIntegerでコンパイル通しましたが、やはり何故か10桁以上は通りません。
なので、例外で”10桁以上の整数値は入力できません”と出すようにします。

**Comment by chinen-eita-FTC** [comment]
@kikuta-reo-FTC 

> そうですね。
> 現在、BIgIntegerでコンパイル通しましたが、やはり何故か10桁以上は通りません。
> なので、例外で”10桁以上の整数値は入力できません”と出すようにします。  

`Integer.parseInt`を実行している箇所があるけどそれが原因じゃない？ 
※最新のコードあがってないから何とも言えないけど

【原因と考えられる箇所】
https://github.com/kikuta-reo-FTC/training/blob/192f2eeedac12723862a7f070857fa60a6acd6ac/new_first_task.java#L34-L35

**Comment by chinen-eita-FTC** [comment]
@kikuta-reo-FTC 
https://github.com/kikuta-reo-FTC/training/blob/c05bc52a30c6d193b3ad5ec627f4d22147aed6dc/main/New_First_Task.java#L1-L54

下記の内容に修正したら桁数の問題解消されると思います。

```
import java.io.*;
import java.math.BigInteger;
/**
*@author Leo Kikuta
*@version java 1.8
 */
class New_First_Task
{	
    public static void main(String[] args) throws IOException
    {
    	
        /**
        * 例外処理が発生した場合再度プログラムを実行
        */
        while(true)
        {
            System.out.println("数字を2つ入力してください");
            //ここの処理に関してはまだ知識不足です。
            BufferedReader kl =new BufferedReader(new InputStreamReader(System.in));

            try
            {
                String str1 = kl.readLine();
                String str2 = kl.readLine();

                BigInteger big1 = new BigInteger(str1);
                BigInteger big2 = new BigInteger(str2);

                System.out.println(Calculate.add(big1, big2));
                
                break;
            }
            //in order to treat this as exception if the type is difference.
            catch(NumberFormatException e){
                System.out.println("数字を入力してください");
            }
            //appear stack trace, that's why acctually this does'nt rise up much.
            catch(IOException n){
                n.printStackTrace();
            }
            // in this case, this treat "0" as a exception.
            catch(IllegalArgumentException c){
                System.out.println("0以外を入力してください");
            }
        }
    }
}
```

**Comment by kikuta-reo-FTC** [comment]
自分も、グーグルで見つけて直せました。
有難う御座います。

**Comment by chinen-eita-FTC** [comment]
最新のコードに反映されたことを確認したため完了
