### ISSUE TITLE
[Ques]文字化け？

### ISSUE THREAD

**Issue by chinen-eita-FTC** [kikuta-reo-FTC/training#6]
https://github.com/kikuta-reo-FTC/training/blob/192f2eeedac12723862a7f070857fa60a6acd6ac/calculate.java#L22

**Comment by kikuta-reo-FTC** [comment]
自分の環境では文字化けしておりません。。

**Comment by chinen-eita-FTC** [comment]
@kikuta-reo-FTC 
成果物として `Github` 上のコードで判断しているけど修正しない感じ？
製品の納品時に同様の理由で相手を納得させれる？

**Comment by kikuta-reo-FTC** [comment]
現在、直して再アップします。
誤解させてしまい申し訳ございません。

**Comment by kikuta-reo-FTC** [comment]
UTF-8からshift-jisに変更いたしました。
再アップロードします。

**Comment by chinen-eita-FTC** [comment]
最新のコードに反映されたことを確認したため完了
