### ISSUE TITLE
[Ques]繰り返し処理の中での変数宣言（＝NUMBER_OF_INPUTS ）必要？

### ISSUE THREAD

**Issue by chinen-eita-FTC** [kikuta-reo-FTC/training#9]
https://github.com/kikuta-reo-FTC/training/blob/192f2eeedac12723862a7f070857fa60a6acd6ac/new_first_task.java#L15-L20

繰り返すたびに宣言する必要がなければ繰り返し処理のスコープ外で変数宣言しよう
→メモリリークの原因になる可能性があるため

**Comment by kikuta-reo-FTC** [comment]
for文で回そうとしてました。。。
消し忘れです。
申し訳ございません

**Comment by chinen-eita-FTC** [comment]
@kikuta-reo-FTC 
はい

**Comment by chinen-eita-FTC** [comment]
最新のコードに反映されたことを確認したため完了
